[package]
name = "pretty_midi_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
midly = "0.5.2"
once_cell = "1.16.0"
thiserror = "1.0.38"
